name: test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
        env:
          DSV_CLIENT_ID: ${{ secrets.DSV_CLIENT_ID }}
          DSV_CLIENT_SECRET: ${{ secrets.DSV_CLIENT_SECRET }}
          DSV_BASE_URL: ${{ secrets.DSV_BASE_URL }}
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          fail_ci_if_error: false
