name: test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
        env:
          DSV_CLIENT_ID: ${{ secrets.DSV_CLIENT_ID }}
          DSV_CLIENT_SECRET: ${{ secrets.DSV_CLIENT_SECRET }}
          DSV_BASE_URL: ${{ secrets.DSV_BASE_URL }}
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
